In [57]:
import pandas as pd
file_1 = pd.read_excel('file_1.xlsx', sheet_name="S.I.T.E Town", skiprows=3, header=1)
file_1.head()

,IDENTIFIER,ENROLLMENTEPINUMBER,CHILDNAME,FATHERNAME,BIRTHDATE,PRIMARYCONTACT,ADDRESS,UC,TOWN/TALUKA,DISTRICT,TOTALDEFAULTED,DEFAULTEDVACCINE,DEFAULTEDVACCINEDUEDATE,DEFAULTEDDATE,STATUS,VACCINATIONDATE,DEFAULTEDVACCINEEVENTTYPE,ENROLLMENTCENTERNAME,ENROLLMENTVACCINATORNAME,DEFAULTEDCENTERNAME
0,20200001732038,20210050.0,NO NAME,Saeed,03-02-2021,NaN,metroville block 3,Metrovil-4,S.I.T.E-1,Kemari District,2,"PENTA2,MEASLES1",05-12-2022,02-01-2023,DEFAULTED,NaN,NaN,Metrolines,Seema Raheem,Metrolines
1,20200001732037,20210051.0,NO NAME,Fareed khan,03-02-2021,3.462614e+09,L.s o1 metroville block 5,Metrovil-4,S.I.T.E-1,Kemari District,2,"PENTA2,MEASLES1",12-07-2022,09-08-2022,DEFAULTED,NaN,NaN,Metrolines,Seema Raheem,Metrolines
2,20200001772043,20211991.0,Jackson,alex,04-02-2021,3.172524e+09,new golimar zimmedar hotel,Old Golimar-2,S.I.T.E-1,Kemari District,1,MEASLES2,07-05-2022,04-06-2022,DEFAULTED,NaN,NaN,Fatmiya Hospital,Anisa zain agha,Pirabad Dispensary
3,20200001731240,20210031.0,NO NAME,Sarwar Khan,09-02-2021,NaN,"786/Street#,10 Laasi Para Meera Naka",Bawani Chali-5,S.I.T.E-1,Kemari District,2,"PENTA1,MEASLES1",23-03-2021,20-04-2021,DEFAULTED,NaN,NaN,K.V Site Hospital,Noor Saba,K.V Site Hospital
4,20200001731244,20210034.0,Ajwah,Sajjad Ali,02-02-2021,3.442780e+09,Tenants KESC969/Ghousia Mohallah Frontier Colo...,Bawani Chali-5,S.I.T.E-1,Kemari District,1,MEASLES2,19-08-2022,16-09-2022,DEFAULTED,NaN,NaN,K.V Site Hospital,Noor Saba,Hassan Jan Hospital

In [58]:
file_2 = pd.read_excel('file_2.xlsx', sheet_name="Keamari Town",skiprows=3, header=1)
file_2.head()

,IDENTIFIER,ENROLLMENTEPINUMBER,CHILDNAME,FATHERNAME,BIRTHDATE,PRIMARYCONTACT,ADDRESS,UC,TOWN/TALUKA,DISTRICT,TOTALDEFAULTED,DEFAULTEDVACCINE,DEFAULTEDVACCINEDUEDATE,DEFAULTEDDATE,STATUS,VACCINATIONDATE,DEFAULTEDVACCINEEVENTTYPE,ENROLLMENTCENTERNAME,ENROLLMENTVACCINATORNAME,DEFAULTEDCENTERNAME
0,20200001465319,20210421.0,Shanzey,Tayyab,01-02-2021,NaN,anre pnad,Gabopat-8,Kemari,Kemari District,2,"PENTA2,MEASLES1",19-04-2021,17-05-2021,DEFAULTED,NaN,NaN,Family Welfare enter,Sadaf Iqbal,Family Welfare enter
1,20202000094283,20210320.0,ayesha,Adil Shahzad,06-02-2021,3.128760e+09,mushraf colony,Maripur-6,Kemari,Kemari District,2,"PENTA3,MEASLES2",08-04-2022,06-05-2022,DEFAULTED,NaN,NaN,Lyari General Hospital,Abdul Rasheed,Lyari General Hospital
2,20202000090050,20210337.0,mehak,mazhar,04-02-2021,3.452596e+09,shershah,Sher Shah-7,Kemari,Kemari District,2,"PENTA1,MEASLES1",18-03-2021,15-04-2021,DEFAULTED,NaN,NaN,Lyari General Hospital,Saima Jadoon,Lyari General Hospital
3,20202000090051,20210338.0,Urooj fatima,Sher ali,04-02-2021,3.153103e+09,sindh makilay,Gabopat-8,Kemari,Kemari District,1,MEASLES2,07-05-2022,04-06-2022,DEFAULTED,NaN,NaN,Lyari General Hospital,Asad Mehmood,Sina Welfare -Mawach Goth
4,20190001630155,20210230.0,Muhammad anas,Najmul alim,01-02-2021,NaN,street 30 muhammadi road,Sher Shah-7,Kemari,Kemari District,1,MEASLES2,04-05-2022,01-06-2022,DEFAULTED,NaN,NaN,RHC Shershah,Noman Ahmed,RHC Shershah

In [69]:
file_3 = pd.read_excel("file_3.xlsx", sheet_name='Baldia Town', skiprows=3, header=1)
file_3.head()
#file_3.rename(columns={'IDENTIFIER':'new_name'}, inplace=True)
#file_3

,IDENTIFIER,ENROLLMENTEPINUMBER,CHILDNAME,FATHERNAME,BIRTHDATE,PRIMARYCONTACT,ADDRESS,UC,TOWN/TALUKA,DISTRICT,TOTALDEFAULTED,DEFAULTEDVACCINE,DEFAULTEDVACCINEDUEDATE,DEFAULTEDDATE,STATUS,VACCINATIONDATE,DEFAULTEDVACCINEEVENTTYPE,ENROLLMENTCENTERNAME,ENROLLMENTVACCINATORNAME,DEFAULTEDCENTERNAME
0,20210000100980,20210343.0,NO NAME,Shahid,01-02-2021,NaN,NaN,Gulshan-e-Ghazi-1,Baldia,Kemari District,2,"PENTA1,MEASLES1",15-03-2021,12-04-2021,DEFAULTED,NaN,NaN,Civil Hospital (Gyne Ward),Muhammad Uzair,Civil Hospital (Gyne Ward)
1,20210000110988,20210319.0,hadiu,Aziz,01-02-2021,3.142578e+09,NaN,Muslim Mujahid Colony,Baldia,Kemari District,1,PENTA2,30-12-2022,27-01-2023,DEFAULTED,NaN,NaN,Civil Hospital (Gyne Ward),Muhammad Uzair,RHC Baldia Town
2,20200001675483,20210015.0,Boy,Waqer,01-02-2021,NaN,Baldia,Gulshan-e-Ghazi-1,Baldia,Kemari District,2,"PENTA1,MEASLES2",11-03-2022,08-04-2022,DEFAULTED,NaN,NaN,Al-Khidmat Hospital,Husna Bano,Al-Khidmat Hospital
3,20210000104948,20215865.0,faizas,Dilawar,02-02-2021,NaN,Baldia,Rasheedabad-8,Baldia,Kemari District,1,PENTA2,30-12-2022,27-01-2023,DEFAULTED,NaN,NaN,JPMC Hospital,Kainat Zehra,RHC Baldia Town
4,20200000740405,20210210.0,khula,Mehboob,04-02-2021,3.181258e+09,NaN,Ittehad Town-2,Baldia,Kemari District,1,MEASLES1,04-11-2021,02-12-2021,DEFAULTED,NaN,NaN,Qatar Hospital Old,Sadaf khan,Qatar Hospital Old

In [70]:
if((file_1.columns.any() == file_2.columns.any()) and (file_1.columns.any() == file_3.columns.any())):
    print("3 tables columns are same")
else:
        print("not same")

3 tables columns are same

In [72]:
file_123= pd.concat([file_1,file_2,file_3])
file_123

,IDENTIFIER,ENROLLMENTEPINUMBER,CHILDNAME,FATHERNAME,BIRTHDATE,PRIMARYCONTACT,ADDRESS,UC,TOWN/TALUKA,DISTRICT,TOTALDEFAULTED,DEFAULTEDVACCINE,DEFAULTEDVACCINEDUEDATE,DEFAULTEDDATE,STATUS,VACCINATIONDATE,DEFAULTEDVACCINEEVENTTYPE,ENROLLMENTCENTERNAME,ENROLLMENTVACCINATORNAME,DEFAULTEDCENTERNAME
0,20200001732038,20210050.0,NO NAME,Saeed,03-02-2021,NaN,metroville block 3,Metrovil-4,S.I.T.E-1,Kemari District,2,"PENTA2,MEASLES1",05-12-2022,02-01-2023,DEFAULTED,NaN,NaN,Metrolines,Seema Raheem,Metrolines
1,20200001732037,20210051.0,NO NAME,Fareed khan,03-02-2021,3.462614e+09,L.s o1 metroville block 5,Metrovil-4,S.I.T.E-1,Kemari District,2,"PENTA2,MEASLES1",12-07-2022,09-08-2022,DEFAULTED,NaN,NaN,Metrolines,Seema Raheem,Metrolines
2,20200001772043,20211991.0,Jackson,alex,04-02-2021,3.172524e+09,new golimar zimmedar hotel,Old Golimar-2,S.I.T.E-1,Kemari District,1,MEASLES2,07-05-2022,04-06-2022,DEFAULTED,NaN,NaN,Fatmiya Hospital,Anisa zain agha,Pirabad Dispensary
3,20200001731240,20210031.0,NO NAME,Sarwar Khan,09-02-2021,NaN,"786/Street#,10 Laasi Para Meera Naka",Bawani Chali-5,S.I.T.E-1,Kemari District,2,"PENTA1,MEASLES1",23-03-2021,20-04-2021,DEFAULTED,NaN,NaN,K.V Site Hospital,Noor Saba,K.V Site Hospital
4,20200001731244,20210034.0,Ajwah,Sajjad Ali,02-02-2021,3.442780e+09,Tenants KESC969/Ghousia Mohallah Frontier Colo...,Bawani Chali-5,S.I.T.E-1,Kemari District,1,MEASLES2,19-08-2022,16-09-2022,DEFAULTED,NaN,NaN,K.V Site Hospital,Noor Saba,Hassan Jan Hospital
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14815,20229002408284,20220000.0,Muraid,Shoukat ali,30-10-2022,NaN,altaf nagar,Ittehad Town-2,Baldia,Kemari District,1,PENTA1,03-01-2023,31-01-2023,DEFAULTED,NaN,NaN,Govt. Dispensary Muhammad Khan Colony,Shazia Aslam,Govt. Dispensary Muhammad Khan Colony
14816,20229002408214,20220000.0,Yasir khan,Ashifaq khan,25-10-2022,NaN,altaf nagr,Ittehad Town-2,Baldia,Kemari District,1,PENTA1,03-01-2023,31-01-2023,DEFAULTED,NaN,NaN,Govt. Dispensary Muhammad Khan Colony,Shazia Aslam,Govt. Dispensary Muhammad Khan Colony
14817,20229002408211,20220000.0,Rizwan,Ramzan,21-11-2022,NaN,altaf nagar,Ittehad Town-2,Baldia,Kemari District,1,PENTA1,02-01-2023,30-01-2023,DEFAULTED,NaN,NaN,Govt. Dispensary Muhammad Khan Colony,Shazia Aslam,Govt. Dispensary Muhammad Khan Colony
14818,20230000000339,20230001.0,Mustafa kamal,Haseeb gul,22-10-2022,NaN,faisal muhalla,Rasheedabad-8,Baldia,Kemari District,1,PENTA1,03-01-2023,31-01-2023,DEFAULTED,NaN,NaN,ZMC Dispensary Rasheedabad,Nadia Huma,ZMC Dispensary Rasheedabad
14819,20230000023386,20230003.0,Nadia,Anwer,01-05-2022,NaN,H F 36,Rasheedabad-8,Baldia,Kemari District,1,PENTA1,03-01-2023,31-01-2023,DEFAULTED,NaN,NaN,ZMC Dispensary Rasheedabad,Nadia Huma,ZMC Dispensary Rasheedabad

<class 'pandas.core.frame.DataFrame'>
Int64Index: 31714 entries, 0 to 14819
Data columns (total 20 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   IDENTIFIER                 31714 non-null  int64
 1   ENROLLMENTEPINUMBER        29646 non-null  float64
 2   CHILDNAME                  31714 non-null  object
 3   FATHERNAME                 31714 non-null  object
 4   BIRTHDATE                  31714 non-null  object
 5   PRIMARYCONTACT             14907 non-null  float64
 6   ADDRESS                    29719 non-null  object
 7   UC                         31714 non-null  object
 8   TOWN/TALUKA                31714 non-null  object
 9   DISTRICT                   31714 non-null  object
 10  TOTALDEFAULTED             31714 non-null  int64
 11  DEFAULTEDVACCINE           31714 non-null  object
 12  DEFAULTEDVACCINEDUEDATE    31714 non-null  object
 13  DEFAULTEDDATE              31714 non-null  object
 14  STATUS                     31714 non-null  object
 15  VACCINATIONDATE            0 non-null      float64
 16  DEFAULTEDVACCINEEVENTTYPE  0 non-null      float64
 17  ENROLLMENTCENTERNAME       31676 non-null  object
 18  ENROLLMENTVACCINATORNAME   31676 non-null  object
 19  DEFAULTEDCENTERNAME        31714 non-null  object
dtypes: float64(4), int64(2), object(14)
memory usage: 5.1+ MB

In [93]:
a=file_123['BIRTHDATE'] = file_123['BIRTHDATE'].astype(str)
a.info()

<class 'pandas.core.series.Series'>
Int64Index: 31714 entries, 0 to 14819
Series name: BIRTHDATE
Non-Null Count  Dtype
--------------  -----
31714 non-null  object
dtypes: object(1)
memory usage: 495.5+ KB

In [94]:
#file_123['BIRTHDATE'] = pd.to_datetime([file_123['BIRTHDATE']])
file_123[['day','month','year']] = file_123['BIRTHDATE'].str.split("-", expand=True)
file_123

,IDENTIFIER,ENROLLMENTEPINUMBER,CHILDNAME,FATHERNAME,BIRTHDATE,PRIMARYCONTACT,ADDRESS,UC,TOWN/TALUKA,DISTRICT,...,DEFAULTEDDATE,STATUS,VACCINATIONDATE,DEFAULTEDVACCINEEVENTTYPE,ENROLLMENTCENTERNAME,ENROLLMENTVACCINATORNAME,DEFAULTEDCENTERNAME,day,month,year
0,20200001732038,20210050.0,NO NAME,Saeed,03-02-2021,NaN,metroville block 3,Metrovil-4,S.I.T.E-1,Kemari District,...,02-01-2023,DEFAULTED,NaN,NaN,Metrolines,Seema Raheem,Metrolines,03,02,2021
1,20200001732037,20210051.0,NO NAME,Fareed khan,03-02-2021,3.462614e+09,L.s o1 metroville block 5,Metrovil-4,S.I.T.E-1,Kemari District,...,09-08-2022,DEFAULTED,NaN,NaN,Metrolines,Seema Raheem,Metrolines,03,02,2021
2,20200001772043,20211991.0,Jackson,alex,04-02-2021,3.172524e+09,new golimar zimmedar hotel,Old Golimar-2,S.I.T.E-1,Kemari District,...,04-06-2022,DEFAULTED,NaN,NaN,Fatmiya Hospital,Anisa zain agha,Pirabad Dispensary,04,02,2021
3,20200001731240,20210031.0,NO NAME,Sarwar Khan,09-02-2021,NaN,"786/Street#,10 Laasi Para Meera Naka",Bawani Chali-5,S.I.T.E-1,Kemari District,...,20-04-2021,DEFAULTED,NaN,NaN,K.V Site Hospital,Noor Saba,K.V Site Hospital,09,02,2021
4,20200001731244,20210034.0,Ajwah,Sajjad Ali,02-02-2021,3.442780e+09,Tenants KESC969/Ghousia Mohallah Frontier Colo...,Bawani Chali-5,S.I.T.E-1,Kemari District,...,16-09-2022,DEFAULTED,NaN,NaN,K.V Site Hospital,Noor Saba,Hassan Jan Hospital,02,02,2021
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14815,20229002408284,20220000.0,Muraid,Shoukat ali,30-10-2022,NaN,altaf nagar,Ittehad Town-2,Baldia,Kemari District,...,31-01-2023,DEFAULTED,NaN,NaN,Govt. Dispensary Muhammad Khan Colony,Shazia Aslam,Govt. Dispensary Muhammad Khan Colony,30,10,2022
14816,20229002408214,20220000.0,Yasir khan,Ashifaq khan,25-10-2022,NaN,altaf nagr,Ittehad Town-2,Baldia,Kemari District,...,31-01-2023,DEFAULTED,NaN,NaN,Govt. Dispensary Muhammad Khan Colony,Shazia Aslam,Govt. Dispensary Muhammad Khan Colony,25,10,2022
14817,20229002408211,20220000.0,Rizwan,Ramzan,21-11-2022,NaN,altaf nagar,Ittehad Town-2,Baldia,Kemari District,...,30-01-2023,DEFAULTED,NaN,NaN,Govt. Dispensary Muhammad Khan Colony,Shazia Aslam,Govt. Dispensary Muhammad Khan Colony,21,11,2022
14818,20230000000339,20230001.0,Mustafa kamal,Haseeb gul,22-10-2022,NaN,faisal muhalla,Rasheedabad-8,Baldia,Kemari District,...,31-01-2023,DEFAULTED,NaN,NaN,ZMC Dispensary Rasheedabad,Nadia Huma,ZMC Dispensary Rasheedabad,22,10,2022
14819,20230000023386,20230003.0,Nadia,Anwer,01-05-2022,NaN,H F 36,Rasheedabad-8,Baldia,Kemari District,...,31-01-2023,DEFAULTED,NaN,NaN,ZMC Dispensary Rasheedabad,Nadia Huma,ZMC Dispensary Rasheedabad,01,05,2022

In [88]:
file_123.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 31714 entries, 0 to 14819
Data columns (total 23 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   IDENTIFIER                 31714 non-null  int64
 1   ENROLLMENTEPINUMBER        29646 non-null  float64
 2   CHILDNAME                  31714 non-null  object
 3   FATHERNAME                 31714 non-null  object
 4   BIRTHDATE                  31714 non-null  object
 5   PRIMARYCONTACT             14907 non-null  float64
 6   ADDRESS                    29719 non-null  object
 7   UC                         31714 non-null  object
 8   TOWN/TALUKA                31714 non-null  object
 9   DISTRICT                   31714 non-null  object
 10  TOTALDEFAULTED             31714 non-null  int64
 11  DEFAULTEDVACCINE           31714 non-null  object
 12  DEFAULTEDVACCINEDUEDATE    31714 non-null  object
 13  DEFAULTEDDATE              31714 non-null  object
 14  STATUS                     31714 non-null  object
 15  VACCINATIONDATE            0 non-null      float64
 16  DEFAULTEDVACCINEEVENTTYPE  0 non-null      float64
 17  ENROLLMENTCENTERNAME       31676 non-null  object
 18  ENROLLMENTVACCINATORNAME   31676 non-null  object
 19  DEFAULTEDCENTERNAME        31714 non-null  object
 20  day                        31714 non-null  object
 21  month                      31714 non-null  object
 22  year                       31714 non-null  object
dtypes: float64(4), int64(2), object(17)
memory usage: 5.8+ MB

In [97]:
file_123['day'] = file_123['day'].astype(int)
file_123['month'] = file_123['month'].astype(int)
file_123['year'] = file_123['year'].astype(int)
file_123.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 31714 entries, 0 to 14819
Data columns (total 23 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   IDENTIFIER                 31714 non-null  int64
 1   ENROLLMENTEPINUMBER        29646 non-null  float64
 2   CHILDNAME                  31714 non-null  object
 3   FATHERNAME                 31714 non-null  object
 4   BIRTHDATE                  31714 non-null  object
 5   PRIMARYCONTACT             14907 non-null  float64
 6   ADDRESS                    29719 non-null  object
 7   UC                         31714 non-null  object
 8   TOWN/TALUKA                31714 non-null  object
 9   DISTRICT                   31714 non-null  object
 10  TOTALDEFAULTED             31714 non-null  int64
 11  DEFAULTEDVACCINE           31714 non-null  object
 12  DEFAULTEDVACCINEDUEDATE    31714 non-null  object
 13  DEFAULTEDDATE              31714 non-null  object
 14  STATUS                     31714 non-null  object
 15  VACCINATIONDATE            0 non-null      float64
 16  DEFAULTEDVACCINEEVENTTYPE  0 non-null      float64
 17  ENROLLMENTCENTERNAME       31676 non-null  object
 18  ENROLLMENTVACCINATORNAME   31676 non-null  object
 19  DEFAULTEDCENTERNAME        31714 non-null  object
 20  day                        31714 non-null  int32
 21  month                      31714 non-null  int32
 22  year                       31714 non-null  int32
dtypes: float64(4), int32(3), int64(2), object(14)
memory usage: 5.4+ MB

In [99]:
file_123['day'].max()

31

In [107]:
#BIRTHDATE = pd.concat([file_123['day'],file_123['month'],file_123['year']], axis=1)
#BIRTHDATE
file_123['BIRTHDATE'] = pd.to_datetime(file_123[['year', 'month', 'day']])
file_123

,IDENTIFIER,ENROLLMENTEPINUMBER,CHILDNAME,FATHERNAME,BIRTHDATE,PRIMARYCONTACT,ADDRESS,UC,TOWN/TALUKA,DISTRICT,...,DEFAULTEDDATE,STATUS,VACCINATIONDATE,DEFAULTEDVACCINEEVENTTYPE,ENROLLMENTCENTERNAME,ENROLLMENTVACCINATORNAME,DEFAULTEDCENTERNAME,day,month,year
0,20200001732038,20210050.0,NO NAME,Saeed,2021-02-03,NaN,metroville block 3,Metrovil-4,S.I.T.E-1,Kemari District,...,02-01-2023,DEFAULTED,NaN,NaN,Metrolines,Seema Raheem,Metrolines,3,2,2021
1,20200001732037,20210051.0,NO NAME,Fareed khan,2021-02-03,3.462614e+09,L.s o1 metroville block 5,Metrovil-4,S.I.T.E-1,Kemari District,...,09-08-2022,DEFAULTED,NaN,NaN,Metrolines,Seema Raheem,Metrolines,3,2,2021
2,20200001772043,20211991.0,Jackson,alex,2021-02-04,3.172524e+09,new golimar zimmedar hotel,Old Golimar-2,S.I.T.E-1,Kemari District,...,04-06-2022,DEFAULTED,NaN,NaN,Fatmiya Hospital,Anisa zain agha,Pirabad Dispensary,4,2,2021
3,20200001731240,20210031.0,NO NAME,Sarwar Khan,2021-02-09,NaN,"786/Street#,10 Laasi Para Meera Naka",Bawani Chali-5,S.I.T.E-1,Kemari District,...,20-04-2021,DEFAULTED,NaN,NaN,K.V Site Hospital,Noor Saba,K.V Site Hospital,9,2,2021
4,20200001731244,20210034.0,Ajwah,Sajjad Ali,2021-02-02,3.442780e+09,Tenants KESC969/Ghousia Mohallah Frontier Colo...,Bawani Chali-5,S.I.T.E-1,Kemari District,...,16-09-2022,DEFAULTED,NaN,NaN,K.V Site Hospital,Noor Saba,Hassan Jan Hospital,2,2,2021
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14815,20229002408284,20220000.0,Muraid,Shoukat ali,2022-10-30,NaN,altaf nagar,Ittehad Town-2,Baldia,Kemari District,...,31-01-2023,DEFAULTED,NaN,NaN,Govt. Dispensary Muhammad Khan Colony,Shazia Aslam,Govt. Dispensary Muhammad Khan Colony,30,10,2022
14816,20229002408214,20220000.0,Yasir khan,Ashifaq khan,2022-10-25,NaN,altaf nagr,Ittehad Town-2,Baldia,Kemari District,...,31-01-2023,DEFAULTED,NaN,NaN,Govt. Dispensary Muhammad Khan Colony,Shazia Aslam,Govt. Dispensary Muhammad Khan Colony,25,10,2022
14817,20229002408211,20220000.0,Rizwan,Ramzan,2022-11-21,NaN,altaf nagar,Ittehad Town-2,Baldia,Kemari District,...,30-01-2023,DEFAULTED,NaN,NaN,Govt. Dispensary Muhammad Khan Colony,Shazia Aslam,Govt. Dispensary Muhammad Khan Colony,21,11,2022
14818,20230000000339,20230001.0,Mustafa kamal,Haseeb gul,2022-10-22,NaN,faisal muhalla,Rasheedabad-8,Baldia,Kemari District,...,31-01-2023,DEFAULTED,NaN,NaN,ZMC Dispensary Rasheedabad,Nadia Huma,ZMC Dispensary Rasheedabad,22,10,2022
14819,20230000023386,20230003.0,Nadia,Anwer,2022-05-01,NaN,H F 36,Rasheedabad-8,Baldia,Kemari District,...,31-01-2023,DEFAULTED,NaN,NaN,ZMC Dispensary Rasheedabad,Nadia Huma,ZMC Dispensary Rasheedabad,1,5,2022

In [108]:
file_123.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 31714 entries, 0 to 14819
Data columns (total 23 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   IDENTIFIER                 31714 non-null  int64
 1   ENROLLMENTEPINUMBER        29646 non-null  float64
 2   CHILDNAME                  31714 non-null  object
 3   FATHERNAME                 31714 non-null  object
 4   BIRTHDATE                  31714 non-null  datetime64[ns]
 5   PRIMARYCONTACT             14907 non-null  float64
 6   ADDRESS                    29719 non-null  object
 7   UC                         31714 non-null  object
 8   TOWN/TALUKA                31714 non-null  object
 9   DISTRICT                   31714 non-null  object
 10  TOTALDEFAULTED             31714 non-null  int64
 11  DEFAULTEDVACCINE           31714 non-null  object
 12  DEFAULTEDVACCINEDUEDATE    31714 non-null  object
 13  DEFAULTEDDATE              31714 non-null  object
 14  STATUS                     31714 non-null  object
 15  VACCINATIONDATE            0 non-null      float64
 16  DEFAULTEDVACCINEEVENTTYPE  0 non-null      float64
 17  ENROLLMENTCENTERNAME       31676 non-null  object
 18  ENROLLMENTVACCINATORNAME   31676 non-null  object
 19  DEFAULTEDCENTERNAME        31714 non-null  object
 20  day                        31714 non-null  int32
 21  month                      31714 non-null  int32
 22  year                       31714 non-null  int32
dtypes: datetime64[ns](1), float64(4), int32(3), int64(2), object(13)
memory usage: 5.4+ MB

In [134]:
file_uni = file_123.drop_duplicates(subset='ENROLLMENTEPINUMBER', keep='first', inplace=False)
file_uni.head(3)

,IDENTIFIER,ENROLLMENTEPINUMBER,CHILDNAME,FATHERNAME,BIRTHDATE,PRIMARYCONTACT,ADDRESS,UC,TOWN/TALUKA,DISTRICT,...,DEFAULTEDDATE,STATUS,VACCINATIONDATE,DEFAULTEDVACCINEEVENTTYPE,ENROLLMENTCENTERNAME,ENROLLMENTVACCINATORNAME,DEFAULTEDCENTERNAME,day,month,year
0,20200001732038,20210050.0,NO NAME,Saeed,2021-02-03,NaN,metroville block 3,Metrovil-4,S.I.T.E-1,Kemari District,...,02-01-2023,DEFAULTED,NaN,NaN,Metrolines,Seema Raheem,Metrolines,3,2,2021
1,20200001732037,20210051.0,NO NAME,Fareed khan,2021-02-03,3.462614e+09,L.s o1 metroville block 5,Metrovil-4,S.I.T.E-1,Kemari District,...,09-08-2022,DEFAULTED,NaN,NaN,Metrolines,Seema Raheem,Metrolines,3,2,2021
2,20200001772043,20211991.0,Jackson,alex,2021-02-04,3.172524e+09,new golimar zimmedar hotel,Old Golimar-2,S.I.T.E-1,Kemari District,...,04-06-2022,DEFAULTED,NaN,NaN,Fatmiya Hospital,Anisa zain agha,Pirabad Dispensary,4,2,2021

In [153]:
col_district = file_123['DISTRICT'].value_counts()
col_district

Kemari District    31714
Name: DISTRICT, dtype: int64

In [143]:
file_123["IDENTIFIER"].duplicated().count()

31714

In [144]:
file_123['TOWN/TALUKA'].nunique()

3

In [173]:
file_final =pd.pivot_table(file_123, index=['TOWN/TALUKA','UC'] ,columns=['DISTRICT'],  values='CHILDNAME',aggfunc='count',margins=True)
file_final

DISTRICT                           Kemari District    All
TOWN/TALUKA UC
Baldia      Gulshan-e-Ghazi-1                 3824   3824
            Islam Nagar-3                     2820   2820
            Ittehad Town-2                    4068   4068
            Muhajir Camp-7                     492    492
            Muslim Mujahid Colony              863    863
            Nai Abadi-4                        577    577
            Rasheedabad-8                      794    794
            Saeedabad-5                       1382   1382
Kemari       Bhutta Village-1                 1648   1648
             Gabopat-8                        2022   2022
            Baba Bhit-4                        385    385
            Kemari-3                          1810   1810
            Machar Colony-5                   2673   2673
            Maripur-6                         1337   1337
            Sher Shah-7                       1854   1854
            Sultanabad-2                      2376   2376
S.I.T.E-1    Bawani Chali-5                    965    965
             Pak Colony-1                      445    445
            Jananabad-3                        147    147
            Metrovil-4                        1049   1049
            Old Golimar-2                      183    183
All                                          31714  31714

In [175]:
file_final.to_csv('pivot.csv')

In [131]:
file_123.to_excel('compile.xlsx')

In [132]:
file_uni.to_excel('unique.xlsx')